project_id = "fkaziwfwangiwnduxymf"

[functions.insert-signal]
verify_jwt = false

[functions.save-push-subscription]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.market-data]
verify_jwt = false

[functions.indicator-alerts]
verify_jwt = false

[functions.symbol-search]
verify_jwt = false
