import { useState, useEffect, useRef } from 'react';
import { PieChart, Pie, Cell, ResponsiveContainer } from 'recharts';
import { Loader2, TrendingUp, TrendingDown, Minus } from 'lucide-react';
import { useMarketSentiment } from '@/hooks/useAnalysisData';
import { useAIAnalysis } from '@/hooks/useAIAnalysis';
import { AnalysisError } from './AnalysisError';
import { AIRegenerateButton } from './AIRegenerateButton';
import { AIRefreshOverlay } from './AIRefreshOverlay';
import { cn } from '@/lib/utils';

interface MarketSentimentProps {
  symbol: string;
  highPrice: number;
  lowPrice: number;
  dailyChange: number;
  pipsChange: number;
  realtimePrice?: number;
  isRealtimeConnected?: boolean;
}

export function MarketSentiment({
  symbol,
  highPrice,
  lowPrice,
  dailyChange,
  pipsChange,
  realtimePrice,
  isRealtimeConnected,
}: MarketSentimentProps) {
  const { data: sentimentData, isLoading, error } = useMarketSentiment(symbol);
  const { generateAnalysis, isLoading: isAILoading } = useAIAnalysis();
  const [aiSentiment, setAISentiment] = useState<Record<string, unknown> | null>(null);
  const prevSymbolRef = useRef<string | null>(null);
  const hasAutoGenerated = useRef(false);

  // Auto-generate AI sentiment when symbol changes
  useEffect(() => {
    if (symbol && symbol !== prevSymbolRef.current) {
      prevSymbolRef.current = symbol;
      hasAutoGenerated.current = false;
      setAISentiment(null);
    }
  }, [symbol]);

  // Auto-generate AI analysis when we have price data and haven't generated yet
  useEffect(() => {
    const currentPrice = realtimePrice || (highPrice + lowPrice) / 2;
    
    if (symbol && currentPrice > 0 && !hasAutoGenerated.current && !isAILoading) {
      hasAutoGenerated.current = true;
      
      generateAnalysis('sentiment', symbol, {
        currentPrice,
        previousClose: currentPrice - (dailyChange / 100),
        high: highPrice,
        low: lowPrice
      }).then(result => {
        if (result?.analysis) {
          setAISentiment(result.analysis);
        }
      });
    }
  }, [symbol, realtimePrice, highPrice, lowPrice, dailyChange, generateAnalysis, isAILoading]);

  const handleRegenerateWithAI = async () => {
    const currentPrice = realtimePrice || (highPrice + lowPrice) / 2;
    const result = await generateAnalysis('sentiment', symbol, {
      currentPrice,
      previousClose: currentPrice - (dailyChange / 100),
      high: highPrice,
      low: lowPrice
    });
    if (result?.analysis) {
      setAISentiment(result.analysis);
    }
  };

  // Use AI data if available, otherwise use API data
  const displayData = aiSentiment || sentimentData;

  const chartData = [
    { name: 'Alcista', value: aiSentiment 
      ? Math.round(((Number(aiSentiment.score) || 0) + 1) / 2 * 100) 
      : (sentimentData?.bullishPercent || 0) as number, color: '#22c55e' },
    { name: 'Neutro', value: aiSentiment 
      ? Math.round((1 - Math.abs(Number(aiSentiment.score) || 0)) * 50) 
      : (sentimentData?.neutralPercent || 0) as number, color: '#eab308' },
    { name: 'Bajista', value: aiSentiment 
      ? Math.round((1 - (Number(aiSentiment.score) || 0)) / 2 * 100) 
      : (sentimentData?.bearishPercent || 0) as number, color: '#ef4444' },
  ];

  // Get the dominant sentiment
  const dominantSentiment = chartData.reduce((prev, current) => 
    (prev.value > current.value) ? prev : current
  );

  const trendInfo = {
    bullish: { icon: TrendingUp, label: 'ALCISTA', color: 'text-green-400' },
    bearish: { icon: TrendingDown, label: 'BAJISTA', color: 'text-red-400' },
    neutral: { icon: Minus, label: 'NEUTRAL', color: 'text-yellow-400' },
  };

  const currentTrend = sentimentData?.overall || 
    (dominantSentiment.name === 'Alcista' ? 'bullish' : 
     dominantSentiment.name === 'Bajista' ? 'bearish' : 'neutral');
  
  const TrendIcon = trendInfo[currentTrend as keyof typeof trendInfo]?.icon || Minus;

  if (isLoading) {
    return (
      <div className="bg-[#0a1a0a] border border-green-900/50 rounded-lg p-4">
        <div className="flex items-center justify-center py-8">
          <Loader2 className="w-6 h-6 text-green-400 animate-spin" />
          <span className="ml-2 text-gray-400">Cargando sentimiento...</span>
        </div>
      </div>
    );
  }

  if (error && !aiSentiment) {
    return (
      <AnalysisError 
        title="Sentimiento del Mercado"
        error={error as Error}
        compact
      />
    );
  }

  return (
    <AIRefreshOverlay isRefreshing={isAILoading}>
      <div className="bg-[#0a1a0a] border border-green-900/50 rounded-lg p-4 relative overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-white font-semibold text-lg">Sentimiento del Mercado</h3>
          <AIRegenerateButton 
            onClick={handleRegenerateWithAI} 
            isLoading={isAILoading}
          />
        </div>

        {aiSentiment && (
          <div className="mb-3 text-xs text-purple-400 flex items-center gap-1">
            <span className="w-2 h-2 bg-purple-400 rounded-full animate-pulse" />
            Análisis generado con IA
          </div>
        )}

        {/* Main Layout: Trend + Chart | Stats + Indicators */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-4">
          
          {/* Left: Compact Trend + Large Chart */}
          <div className="lg:col-span-5 flex gap-3">
            {/* Compact Trend Indicator */}
            <div className={cn(
              "flex flex-col items-center justify-center px-3 py-2 rounded-xl border transition-all shrink-0",
              currentTrend === 'bullish' 
                ? 'bg-green-900/20 border-green-500/40' 
                : currentTrend === 'bearish' 
                ? 'bg-red-900/20 border-red-500/40'
                : 'bg-yellow-900/20 border-yellow-500/40'
            )}>
              <TrendIcon className={cn(
                "w-6 h-6",
                trendInfo[currentTrend as keyof typeof trendInfo]?.color
              )} />
              <div className={cn(
                "text-sm font-bold mt-1",
                trendInfo[currentTrend as keyof typeof trendInfo]?.color
              )}>
                {trendInfo[currentTrend as keyof typeof trendInfo]?.label}
              </div>
              <div className="text-lg font-bold text-white">
                {dominantSentiment.value}%
              </div>
            </div>

            {/* Large Pie Chart */}
            <div className="flex-1">
              <div className="h-52">
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie
                      data={chartData}
                      cx="50%"
                      cy="50%"
                      innerRadius={50}
                      outerRadius={85}
                      paddingAngle={3}
                      dataKey="value"
                    >
                      {chartData.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={entry.color} />
                      ))}
                    </Pie>
                  </PieChart>
                </ResponsiveContainer>
              </div>
              {/* Legend */}
              <div className="flex justify-center gap-4 mt-2">
                {chartData.map((item) => (
                  <div key={item.name} className="flex items-center gap-1">
                    <div className="w-2 h-2 rounded-full" style={{ backgroundColor: item.color }} />
                    <span className="text-[10px] text-gray-400">{item.name}</span>
                    <span className="text-xs font-bold" style={{ color: item.color }}>{item.value}%</span>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Right: Stats + Indicators Grid */}
          <div className="lg:col-span-7">
            <div className="grid grid-cols-4 gap-2">
              {/* Price Stats */}
              <div className="bg-green-900/10 border border-green-900/30 rounded-lg p-2 text-center">
                <span className="text-gray-400 text-[10px] block">Máximo</span>
                <div className="text-green-400 text-sm font-bold font-mono">{highPrice.toFixed(4)}</div>
              </div>
              <div className="bg-red-900/10 border border-red-900/30 rounded-lg p-2 text-center">
                <span className="text-gray-400 text-[10px] block">Mínimo</span>
                <div className="text-red-400 text-sm font-bold font-mono">{lowPrice.toFixed(4)}</div>
              </div>
              <div className="bg-gray-900/30 border border-gray-700/30 rounded-lg p-2 text-center">
                <span className="text-gray-400 text-[10px] block">Cambio</span>
                <div className={`text-sm font-bold ${dailyChange >= 0 ? 'text-green-400' : 'text-red-400'}`}>
                  {dailyChange >= 0 ? '+' : ''}{dailyChange.toFixed(2)}%
                </div>
              </div>
              <div className="bg-gray-900/30 border border-gray-700/30 rounded-lg p-2 text-center">
                <span className="text-gray-400 text-[10px] block">Pips</span>
                <div className={`text-sm font-bold ${pipsChange >= 0 ? 'text-green-400' : 'text-red-400'}`}>
                  {pipsChange >= 0 ? '+' : ''}{(pipsChange * 10000).toFixed(0)}
                </div>
              </div>

              {/* Technical Indicators */}
              {sentimentData?.indicators && sentimentData.indicators.slice(0, 4).map((indicator, i) => (
                <div 
                  key={i}
                  className={`rounded-lg p-2 text-center ${
                    indicator.signal === 'buy' ? 'bg-green-900/20 border border-green-900/40' :
                    indicator.signal === 'sell' ? 'bg-red-900/20 border border-red-900/40' :
                    'bg-yellow-900/20 border border-yellow-900/40'
                  }`}
                >
                  <div className="text-[10px] text-gray-400">{indicator.name}</div>
                  <div className={`text-xs font-semibold ${
                    indicator.signal === 'buy' ? 'text-green-400' :
                    indicator.signal === 'sell' ? 'text-red-400' : 'text-yellow-400'
                  }`}>
                    {indicator.signal === 'buy' ? 'Compra' : indicator.signal === 'sell' ? 'Venta' : 'Neutro'}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </AIRefreshOverlay>
  );
}
