import { useState, useEffect, useRef } from 'react';
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible';
import { ChevronDown, Loader2 } from 'lucide-react';
import { useMarketConclusions } from '@/hooks/useAnalysisData';
import { useAIAnalysis } from '@/hooks/useAIAnalysis';
import { AnalysisError } from './AnalysisError';

import { AIRefreshOverlay } from './AIRefreshOverlay';
import { useTranslation } from '@/i18n/LanguageContext';

interface ConclusionItem {
  title: string;
  direction: string;
  probability: number;
  target: number;
}

interface ConclusionRangeItem {
  title: string;
  direction: string;
  probability: number;
  range: {
    min: number;
    max: number;
  };
}

interface MarketConclusionsData {
  shortTerm: ConclusionItem;
  mediumTerm: ConclusionRangeItem;
  longTerm: ConclusionItem;
  technicalSummary: string;
  bullishScenario: string;
  bearishScenario: string;
}

interface UseMarketConclusionsResult {
  data: MarketConclusionsData | null;
  isLoading: boolean;
  error: any;
}

interface AIAnalysisResult {
  analysis: Record<string, unknown> | null;
}

interface UseAIAnalysisResult {
  generateAnalysis: (
    analysisType: string,
    symbol: string,
    options?: Record<string, unknown>,
    language?: string,
    signal?: AbortSignal,
    force?: boolean
  ) => Promise<AIAnalysisResult | undefined>;
  isLoading: boolean;
  error: any;
}

interface MarketConclusionsProps {
  symbol: string;
  currentPrice: number;
  realtimePrice?: number;
  isRealtimeConnected?: boolean;
}

export function MarketConclusions({ symbol, currentPrice, realtimePrice, isRealtimeConnected }: MarketConclusionsProps) {
  const { t } = useTranslation();
  const [isOpen, setIsOpen] = useState(false);
  const { data, isLoading, error } = useMarketConclusions(symbol, currentPrice);
  const { generateAnalysis, isLoading: isAILoading } = useAIAnalysis();
  const [aiConclusions, setAIConclusions] = useState<Record<string, unknown> | null>(null);
  const prevSymbolRef = useRef<string | null>(null);
  const hasAutoGenerated = useRef(false);

  useEffect(() => {
    if (symbol && symbol !== prevSymbolRef.current) {
      prevSymbolRef.current = symbol;
      hasAutoGenerated.current = false;
      setAIConclusions(null);
    }
  }, [symbol]);

  useEffect(() => {
    const price = realtimePrice || currentPrice;
    
    if (symbol && price > 0 && !hasAutoGenerated.current && !isAILoading) {
      hasAutoGenerated.current = true;
      
      generateAnalysis('conclusions', symbol, {
        currentPrice: price,
        previousClose: price * 0.998,
        high: price * 1.005,
        low: price * 0.995
      }).then(result => {
        if (result?.analysis) {
          setAIConclusions(result.analysis);
        }
      });
    }
  }, [symbol, realtimePrice, currentPrice, generateAnalysis, isAILoading]);

  const handleRegenerateWithAI = async () => {
    const price = realtimePrice || currentPrice;
    const result = await generateAnalysis('conclusions', symbol, {
      currentPrice: price,
      previousClose: price * 0.998,
      high: price * 1.005,
      low: price * 0.995
    });
    if (result?.analysis) {
      setAIConclusions(result.analysis);
    }
  };

  const getDirectionColor = (direction: string) => {
    switch (direction) {
      case 'bullish': return 'text-green-400';
      case 'bearish': return 'text-red-400';
      default: return 'text-yellow-400';
    }
  };

  return (
    <AIRefreshOverlay isRefreshing={isAILoading}>
      <Collapsible open={isOpen} onOpenChange={setIsOpen} className="rounded-xl overflow-hidden border border-cyan-800/30">
      <CollapsibleTrigger className="w-full bg-slate-800/60 px-4 py-3 flex items-center justify-between hover:bg-slate-700/60 transition-colors">
        <div className="flex items-center gap-2">
          <h3 className="text-white font-semibold text-sm">{t('analysis_conclusions')}</h3>
          {aiConclusions && (
            <span className="text-xs text-purple-400 bg-purple-500/20 px-2 py-0.5 rounded">IA</span>
          )}
        </div>
        <div className="flex items-center gap-2">
        </div>
      </CollapsibleTrigger>
      
      <CollapsibleContent>
        <div className="p-4 border-t border-cyan-800/30">
          {isLoading ? (
            <div className="flex items-center justify-center py-8">
              <Loader2 className="w-6 h-6 text-cyan-400 animate-spin" />
              <span className="ml-2 text-gray-400">{t('analysis_loading_conclusions')}</span>
            </div>
          ) : error || (!data && !aiConclusions) ? (
            <AnalysisError 
              title={t('analysis_conclusions')}
              error={error as Error}
              compact
            />
          ) : aiConclusions ? (
            <div className="space-y-4">
              <div>
                <p className="text-gray-400 text-sm">{t('analysis_summary')}:</p>
                <p className="text-white">{aiConclusions.summary as string}</p>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <p className="text-gray-400 text-sm mb-2">{t('analysis_key_factors')}:</p>
                  <ul className="text-cyan-400 text-sm list-disc list-inside">
                    {(aiConclusions.key_drivers as string[])?.map((driver, i) => (
                      <li key={i}>{driver}</li>
                    ))}
                  </ul>
                </div>
                <div>
                  <p className="text-gray-400 text-sm mb-2">{t('analysis_risks')}:</p>
                  <ul className="text-red-400 text-sm list-disc list-inside">
                    {(aiConclusions.risks as string[])?.map((risk, i) => (
                      <li key={i}>{risk}</li>
                    ))}
                  </ul>
                </div>
              </div>
              <div>
                <p className="text-gray-400 text-sm mb-2">{t('analysis_opportunities')}:</p>
                <ul className="text-yellow-400 text-sm list-disc list-inside">
                  {(aiConclusions.opportunities as string[])?.map((opp, i) => (
                    <li key={i}>{opp}</li>
                  ))}
                </ul>
              </div>
              <div className="pt-2 border-t border-slate-700/30">
                <p className="text-gray-400 text-sm">{t('analysis_outlook')}:</p>
                <p className="text-white font-semibold">{aiConclusions.outlook as string}</p>
              </div>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="space-y-4">
                <h4 className="text-white font-semibold border-b border-slate-700/50 pb-2">
                  {t('analysis_expected_direction')}
                </h4>
                
                <div className="space-y-3 text-sm">
                  <div>
                    <p className="text-gray-400">{t('analysis_very_short_term')}:</p>
                    <p className={`font-semibold ${getDirectionColor(data!.shortTerm.direction)}`}>
                      {data!.shortTerm.label}
                    </p>
                    <p className="text-gray-300 text-xs">
                      {t('analysis_probability_label')}: {data!.shortTerm.probability}% | {t('analysis_target_label')}: {data!.shortTerm.target.toFixed(4)}
                    </p>
                  </div>
                  
                  <div>
                    <p className="text-gray-400">{t('analysis_short_term')}:</p>
                    <p className={`font-semibold ${getDirectionColor(data!.mediumTerm.direction)}`}>
                      {data!.mediumTerm.label}
                    </p>
                    <p className="text-gray-300 text-xs">
                      {t('analysis_probability_label')}: {data!.mediumTerm.probability}% | {t('analysis_range_label')}: {data!.mediumTerm.range.min.toFixed(4)}-{data!.mediumTerm.range.max.toFixed(4)}
                    </p>
                  </div>
                  
                  <div>
                    <p className="text-gray-400">{t('analysis_medium_term')}:</p>
                    <p className={`font-semibold ${getDirectionColor(data!.longTerm.direction)}`}>
                      {data!.longTerm.label}
                    </p>
                    <p className="text-gray-300 text-xs">
                      {t('analysis_target_label')}: {data!.longTerm.target.toFixed(4)}
                    </p>
                  </div>
                </div>
              </div>

              <div className="space-y-4">
                <h4 className="text-white font-semibold border-b border-slate-700/50 pb-2">
                  {t('analysis_detailed_technical')}
                </h4>
                
                <div className="space-y-3 text-sm">
                  <div>
                    <p className="text-gray-400">{t('analysis_technical_summary')}:</p>
                    <p className="text-gray-300 text-xs">{data!.technicalSummary}</p>
                  </div>
                  
                  <div>
                    <p className="text-gray-400">{t('analysis_for_bulls')}:</p>
                    <p className="text-green-400 text-xs">{data!.bullishScenario}</p>
                  </div>
                  
                  <div>
                    <p className="text-gray-400">{t('analysis_bearish_scenario')}:</p>
                    <p className="text-red-400 text-xs">{data!.bearishScenario}</p>
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>
      </CollapsibleContent>
      </Collapsible>
    </AIRefreshOverlay>
  );
}
