import { useState, useEffect, useRef } from 'react';
import { BarChart, Bar, XAxis, YAxis, ResponsiveContainer, Cell } from 'recharts';
import { Loader2, TrendingUp, TrendingDown, Minus, ChevronUp, ChevronDown } from 'lucide-react';
import { useMarketSentiment } from '@/hooks/useAnalysisData';
import { useAIAnalysis } from '@/hooks/useAIAnalysis';
import { AnalysisError } from './AnalysisError';
import { AIRegenerateButton } from './AIRegenerateButton';
import { AIRefreshOverlay } from './AIRefreshOverlay';
import { ConfettiEffect, SparkleEffect } from './ConfettiEffect';
import { cn } from '@/lib/utils';

interface MarketSentimentProps {
  symbol: string;
  highPrice: number;
  lowPrice: number;
  dailyChange: number;
  pipsChange: number;
  realtimePrice?: number;
  isRealtimeConnected?: boolean;
}

export function MarketSentiment({
  symbol,
  highPrice,
  lowPrice,
  dailyChange,
  pipsChange,
  realtimePrice,
  isRealtimeConnected,
}: MarketSentimentProps) {
  const { data: sentimentData, isLoading, error } = useMarketSentiment(symbol);
  const { generateAnalysis, isLoading: isAILoading } = useAIAnalysis();
  const [aiSentiment, setAISentiment] = useState<Record<string, unknown> | null>(null);
  const [showConfetti, setShowConfetti] = useState(false);
  const prevSentimentRef = useRef<string | null>(null);
  const prevSymbolRef = useRef<string | null>(null);
  const hasAutoGenerated = useRef(false);

  // Auto-generate AI sentiment when symbol changes
  useEffect(() => {
    if (symbol && symbol !== prevSymbolRef.current) {
      prevSymbolRef.current = symbol;
      hasAutoGenerated.current = false;
      setAISentiment(null);
    }
  }, [symbol]);

  // Auto-generate AI analysis when we have price data and haven't generated yet
  useEffect(() => {
    const currentPrice = realtimePrice || (highPrice + lowPrice) / 2;
    
    if (symbol && currentPrice > 0 && !hasAutoGenerated.current && !isAILoading) {
      hasAutoGenerated.current = true;
      
      generateAnalysis('sentiment', symbol, {
        currentPrice,
        previousClose: currentPrice - (dailyChange / 100),
        high: highPrice,
        low: lowPrice
      }).then(result => {
        if (result?.analysis) {
          setAISentiment(result.analysis);
        }
      });
    }
  }, [symbol, realtimePrice, highPrice, lowPrice, dailyChange, generateAnalysis, isAILoading]);

  // Confetti effect for strong bullish sentiment
  useEffect(() => {
    if (sentimentData?.overall) {
      const wasNotBullish = prevSentimentRef.current !== 'bullish';
      const isNowStrongBullish = sentimentData.overall === 'bullish' && (sentimentData.bullishPercent || 0) >= 60;
      
      if (wasNotBullish && isNowStrongBullish) {
        setShowConfetti(true);
        setTimeout(() => setShowConfetti(false), 100);
      }
      
      prevSentimentRef.current = sentimentData.overall;
    }
  }, [sentimentData?.overall, sentimentData?.bullishPercent]);

  const handleRegenerateWithAI = async () => {
    const currentPrice = realtimePrice || (highPrice + lowPrice) / 2;
    const result = await generateAnalysis('sentiment', symbol, {
      currentPrice,
      previousClose: currentPrice - (dailyChange / 100),
      high: highPrice,
      low: lowPrice
    });
    if (result?.analysis) {
      setAISentiment(result.analysis);
    }
  };

  // Use AI data if available, otherwise use API data
  const displayData = aiSentiment || sentimentData;

  // Check for strong bullish sentiment change
  const isStrongBullish = sentimentData?.overall === 'bullish' && (sentimentData?.bullishPercent || 0) >= 60;

  const chartData = [
    { name: 'Alcista', value: aiSentiment 
      ? Math.round(((Number(aiSentiment.score) || 0) + 1) / 2 * 100) 
      : (sentimentData?.bullishPercent || 0) as number, color: '#22c55e' },
    { name: 'Neutro', value: aiSentiment 
      ? Math.round((1 - Math.abs(Number(aiSentiment.score) || 0)) * 50) 
      : (sentimentData?.neutralPercent || 0) as number, color: '#eab308' },
    { name: 'Bajista', value: aiSentiment 
      ? Math.round((1 - (Number(aiSentiment.score) || 0)) / 2 * 100) 
      : (sentimentData?.bearishPercent || 0) as number, color: '#ef4444' },
  ];

  if (isLoading) {
    return (
      <div className="bg-[#0a1a0a] border border-green-900/50 rounded-lg p-4">
        <div className="flex items-center justify-center py-8">
          <Loader2 className="w-6 h-6 text-green-400 animate-spin" />
          <span className="ml-2 text-gray-400">Cargando sentimiento...</span>
        </div>
      </div>
    );
  }

  if (error && !aiSentiment) {
    return (
      <AnalysisError 
        title="Sentimiento del Mercado"
        error={error as Error}
        compact
      />
    );
  }

  return (
    <AIRefreshOverlay isRefreshing={isAILoading}>
      <div className="bg-[#0a1a0a] border border-green-900/50 rounded-lg p-4 relative overflow-hidden">
        {/* Confetti Effect for Strong Bullish */}
        <ConfettiEffect trigger={showConfetti} />
        <SparkleEffect active={isStrongBullish} />
        {/* Header */}
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-white font-semibold text-lg">Sentimiento del Mercado</h3>
          <AIRegenerateButton 
            onClick={handleRegenerateWithAI} 
            isLoading={isAILoading}
          />
        </div>

        {aiSentiment && (
          <div className="mb-3 text-xs text-purple-400 flex items-center gap-1">
            <span className="w-2 h-2 bg-purple-400 rounded-full animate-pulse" />
            Análisis generado con IA
          </div>
        )}

        {/* Animated Trend Indicator */}
        {sentimentData && (
          <div className="flex justify-center mb-4">
            <div className={cn(
              "relative flex flex-col items-center px-8 py-4 rounded-2xl border-2 transition-all duration-500",
              sentimentData.overall === 'bullish' 
                ? 'bg-gradient-to-b from-green-900/40 to-green-900/10 border-green-500/50' 
                : sentimentData.overall === 'bearish' 
                ? 'bg-gradient-to-b from-red-900/40 to-red-900/10 border-red-500/50'
                : 'bg-gradient-to-b from-yellow-900/40 to-yellow-900/10 border-yellow-500/50'
            )}>
              {/* Animated Arrows */}
              <div className="relative h-12 w-12 flex items-center justify-center">
                {sentimentData.overall === 'bullish' && (
                  <>
                    <ChevronUp className="absolute w-8 h-8 text-green-400 animate-bounce" style={{ animationDelay: '0ms' }} />
                    <ChevronUp className="absolute w-8 h-8 text-green-400/60 -top-2 animate-bounce" style={{ animationDelay: '150ms' }} />
                    <ChevronUp className="absolute w-8 h-8 text-green-400/30 -top-4 animate-bounce" style={{ animationDelay: '300ms' }} />
                  </>
                )}
                {sentimentData.overall === 'bearish' && (
                  <>
                    <ChevronDown className="absolute w-8 h-8 text-red-400 animate-bounce" style={{ animationDelay: '0ms' }} />
                    <ChevronDown className="absolute w-8 h-8 text-red-400/60 top-2 animate-bounce" style={{ animationDelay: '150ms' }} />
                    <ChevronDown className="absolute w-8 h-8 text-red-400/30 top-4 animate-bounce" style={{ animationDelay: '300ms' }} />
                  </>
                )}
                {sentimentData.overall === 'neutral' && (
                  <div className="flex items-center gap-1">
                    <Minus className="w-6 h-6 text-yellow-400 animate-pulse" />
                    <Minus className="w-6 h-6 text-yellow-400/60 animate-pulse" style={{ animationDelay: '200ms' }} />
                  </div>
                )}
              </div>
              
              {/* Trend Label */}
              <div className={cn(
                "text-xl font-bold mt-1",
                sentimentData.overall === 'bullish' ? 'text-green-400' :
                sentimentData.overall === 'bearish' ? 'text-red-400' : 'text-yellow-400'
              )}>
                {sentimentData.overall === 'bullish' ? 'ALCISTA' :
                 sentimentData.overall === 'bearish' ? 'BAJISTA' : 'NEUTRAL'}
              </div>
              
              {/* Confidence indicator */}
              <div className="flex items-center gap-2 mt-2">
                <div className="flex gap-0.5">
                  {[1, 2, 3, 4, 5].map((i) => {
                    const strength = sentimentData.overall === 'bullish' 
                      ? sentimentData.bullishPercent 
                      : sentimentData.overall === 'bearish' 
                      ? sentimentData.bearishPercent 
                      : sentimentData.neutralPercent;
                    const filled = i <= Math.ceil(strength / 20);
                    return (
                      <div 
                        key={i}
                        className={cn(
                          "w-2 h-4 rounded-sm transition-all",
                          filled ? (
                            sentimentData.overall === 'bullish' ? 'bg-green-400' :
                            sentimentData.overall === 'bearish' ? 'bg-red-400' : 'bg-yellow-400'
                          ) : 'bg-gray-700'
                        )}
                        style={{ 
                          animationDelay: `${i * 100}ms`,
                          opacity: filled ? 1 : 0.3
                        }}
                      />
                    );
                  })}
                </div>
                <span className="text-xs text-gray-400">
                  {sentimentData.overall === 'bullish' ? sentimentData.bullishPercent :
                   sentimentData.overall === 'bearish' ? sentimentData.bearishPercent : sentimentData.neutralPercent}%
                </span>
              </div>
            </div>
          </div>
        )}

        {/* Main Content Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
          {/* Sentiment Chart */}
          <div className="lg:col-span-1">
            <div className="h-28">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={chartData} layout="horizontal">
                  <XAxis dataKey="name" tick={{ fill: '#9ca3af', fontSize: 10 }} axisLine={false} tickLine={false} />
                  <YAxis hide domain={[0, 100]} />
                  <Bar dataKey="value" radius={[4, 4, 0, 0]}>
                    {chartData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </div>
            <div className="flex justify-around mt-2">
              {chartData.map((item) => (
                <div key={item.name} className="text-center">
                  <div className="text-[10px] text-gray-500">{item.name}</div>
                  <div className="text-sm font-bold" style={{ color: item.color }}>{item.value}%</div>
                </div>
              ))}
            </div>
          </div>

          {/* Price Stats - 2x2 Grid */}
          <div className="lg:col-span-1">
            <div className="grid grid-cols-2 gap-3">
              <div className="bg-green-900/10 border border-green-900/30 rounded-lg p-3 text-center">
                <span className="text-gray-400 text-xs block">Máximo</span>
                <div className="text-green-400 text-xl font-bold font-mono">{highPrice.toFixed(4)}</div>
              </div>
              <div className="bg-red-900/10 border border-red-900/30 rounded-lg p-3 text-center">
                <span className="text-gray-400 text-xs block">Mínimo</span>
                <div className="text-red-400 text-xl font-bold font-mono">{lowPrice.toFixed(4)}</div>
              </div>
              <div className="bg-gray-900/30 border border-gray-700/30 rounded-lg p-3 text-center">
                <span className="text-gray-400 text-xs block">Cambio</span>
                <div className={`text-lg font-bold ${dailyChange >= 0 ? 'text-green-400' : 'text-red-400'}`}>
                  {dailyChange >= 0 ? '+' : ''}{dailyChange.toFixed(2)}%
                </div>
              </div>
              <div className="bg-gray-900/30 border border-gray-700/30 rounded-lg p-3 text-center">
                <span className="text-gray-400 text-xs block">Pips</span>
                <div className={`text-lg font-bold ${pipsChange >= 0 ? 'text-green-400' : 'text-red-400'}`}>
                  {pipsChange >= 0 ? '+' : ''}{(pipsChange * 10000).toFixed(0)}
                </div>
              </div>
            </div>
          </div>

          {/* Indicators */}
          <div className="lg:col-span-1">
            {sentimentData?.indicators && sentimentData.indicators.length > 0 && (
              <div className="h-full flex flex-col">
                <p className="text-xs text-gray-400 mb-2">Indicadores Técnicos:</p>
                <div className="flex-1 grid grid-cols-2 gap-2">
                  {sentimentData.indicators.slice(0, 4).map((indicator, i) => (
                    <div 
                      key={i}
                      className={`rounded-lg p-2 text-center ${
                        indicator.signal === 'buy' ? 'bg-green-900/20 border border-green-900/40' :
                        indicator.signal === 'sell' ? 'bg-red-900/20 border border-red-900/40' :
                        'bg-yellow-900/20 border border-yellow-900/40'
                      }`}
                    >
                      <div className="text-[10px] text-gray-400">{indicator.name}</div>
                      <div className={`text-xs font-semibold ${
                        indicator.signal === 'buy' ? 'text-green-400' :
                        indicator.signal === 'sell' ? 'text-red-400' : 'text-yellow-400'
                      }`}>
                        {indicator.signal === 'buy' ? 'Compra' : indicator.signal === 'sell' ? 'Venta' : 'Neutro'}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </AIRefreshOverlay>
  );
}
