import { useState, useEffect, useRef } from 'react';
import { format } from 'date-fns';
import { es } from 'date-fns/locale';
import { Loader2, TrendingUp, TrendingDown, Minus } from 'lucide-react';
import { usePricePrediction } from '@/hooks/useAnalysisData';
import { useAIAnalysis } from '@/hooks/useAIAnalysis';
import { AnalysisError } from './AnalysisError';
import { AIRegenerateButton } from './AIRegenerateButton';
import { AIRefreshOverlay } from './AIRefreshOverlay';

interface PricePredictionProps {
  symbol: string;
  currentPrice: number;
  realtimePrice?: number;
  isRealtimeConnected?: boolean;
}

export function PricePrediction({ symbol, currentPrice, realtimePrice, isRealtimeConnected }: PricePredictionProps) {
  const { data, isLoading, error } = usePricePrediction(symbol, currentPrice);
  const { generateAnalysis, isLoading: isAILoading } = useAIAnalysis();
  const [aiPrediction, setAIPrediction] = useState<Record<string, unknown> | null>(null);
  const prevSymbolRef = useRef<string | null>(null);
  const hasAutoGenerated = useRef(false);

  // Auto-generate AI prediction when symbol changes
  useEffect(() => {
    if (symbol && symbol !== prevSymbolRef.current) {
      prevSymbolRef.current = symbol;
      hasAutoGenerated.current = false;
      setAIPrediction(null);
    }
  }, [symbol]);

  // Auto-generate AI analysis when we have price data and haven't generated yet
  useEffect(() => {
    const price = realtimePrice || currentPrice;
    
    if (symbol && price > 0 && !hasAutoGenerated.current && !isAILoading) {
      hasAutoGenerated.current = true;
      
      generateAnalysis('prediction', symbol, {
        currentPrice: price,
        previousClose: price * 0.998,
        high: price * 1.005,
        low: price * 0.995
      }).then(result => {
        if (result?.analysis) {
          setAIPrediction(result.analysis);
        }
      });
    }
  }, [symbol, realtimePrice, currentPrice, generateAnalysis, isAILoading]);

  const handleRegenerateWithAI = async () => {
    const price = realtimePrice || currentPrice;
    const result = await generateAnalysis('prediction', symbol, {
      currentPrice: price,
      previousClose: price * 0.998,
      high: price * 1.005,
      low: price * 0.995
    });
    if (result?.analysis) {
      setAIPrediction(result.analysis);
    }
  };

  const today = new Date();
  const dateStr = format(today, "d 'de' MMMM 'de' yyyy", { locale: es });
  
  // Merge AI prediction with data if available
  const displayData = aiPrediction ? {
    ...data,
    predictedHigh: (aiPrediction.predicted_high as number) || data?.predictedHigh,
    predictedLow: (aiPrediction.predicted_low as number) || data?.predictedLow,
    predictedClose: (aiPrediction.predicted_close as number) || data?.predictedClose,
    confidence: (aiPrediction.confidence as number) || data?.confidence,
    summary: (aiPrediction.summary as string) || data?.summary,
    direction: (aiPrediction.direction as string) || data?.direction,
  } : data;

  if (isLoading) {
    return (
      <div className="bg-[#0a1a0a] border border-green-900/50 rounded-lg p-4">
        <div className="flex items-center justify-center py-8">
          <Loader2 className="w-6 h-6 text-green-400 animate-spin" />
          <span className="ml-2 text-gray-400">Cargando predicción...</span>
        </div>
      </div>
    );
  }

  if (error || !displayData) {
    return (
      <AnalysisError 
        title="Predicción del Precio"
        error={error as Error}
        compact
      />
    );
  }

  const trendIcon = displayData.direction === 'up' ? <TrendingUp className="w-5 h-5" /> :
                    displayData.direction === 'down' ? <TrendingDown className="w-5 h-5" /> :
                    <Minus className="w-5 h-5" />;
  
  const trendColor = displayData.direction === 'up' ? 'text-green-400' : 
                     displayData.direction === 'down' ? 'text-red-400' : 'text-yellow-400';
  
  const trendText = displayData.direction === 'up' ? 'Tendencia Alcista' : 
                    displayData.direction === 'down' ? 'Tendencia Bajista' : 'Tendencia Lateral';

  return (
    <AIRefreshOverlay isRefreshing={isAILoading}>
      <div className="bg-[#0a1a0a] border border-green-900/50 rounded-lg p-4">
        <div className="flex items-center justify-between mb-3 flex-wrap gap-2">
          <div className="flex items-center gap-2">
            <h3 className="text-white font-semibold flex items-center gap-2">
              Predicción Del Precio
              {aiPrediction && (
                <span className="text-xs text-purple-400 bg-purple-500/20 px-2 py-0.5 rounded">IA</span>
              )}
            </h3>
            <AIRegenerateButton 
              onClick={handleRegenerateWithAI} 
              isLoading={isAILoading}
              showLabel={false}
              size="icon"
              className="h-7 w-7"
            />
          </div>
          <div className="flex items-center gap-2">
            <span className={`flex items-center gap-1 ${trendColor}`}>
              {trendIcon}
            </span>
            <span className="text-green-400 text-2xl font-bold font-mono">{displayData.currentPrice.toFixed(4)}</span>
          </div>
        </div>

        {/* Predicted range */}
        <div className="grid grid-cols-3 gap-4 mb-4 p-3 bg-[#0d1f0d] rounded-lg">
          <div className="text-center">
            <p className="text-gray-400 text-xs mb-1">Mínimo Esperado</p>
            <p className="text-red-400 font-mono font-semibold">{displayData.predictedLow.toFixed(4)}</p>
          </div>
          <div className="text-center">
            <p className="text-gray-400 text-xs mb-1">Cierre Esperado</p>
            <p className="text-white font-mono font-semibold">{displayData.predictedClose.toFixed(4)}</p>
          </div>
          <div className="text-center">
            <p className="text-gray-400 text-xs mb-1">Máximo Esperado</p>
            <p className="text-green-400 font-mono font-semibold">{displayData.predictedHigh.toFixed(4)}</p>
          </div>
        </div>

        {/* Confidence bar */}
        <div className="mb-4">
          <div className="flex justify-between text-xs mb-1">
            <span className="text-gray-400">Confianza de la predicción</span>
            <span className={`font-semibold ${
              displayData.confidence >= 70 ? 'text-green-400' : 
              displayData.confidence >= 50 ? 'text-yellow-400' : 'text-red-400'
            }`}>{displayData.confidence}%</span>
          </div>
          <div className="h-2 bg-gray-800 rounded-full overflow-hidden">
            <div 
              className={`h-full rounded-full transition-all duration-500 ${
                displayData.confidence >= 70 ? 'bg-green-500' : 
                displayData.confidence >= 50 ? 'bg-yellow-500' : 'bg-red-500'
              }`}
              style={{ width: `${displayData.confidence}%` }}
            />
          </div>
        </div>

        <div className="space-y-3 text-sm">
          <div>
            <h4 className="text-white font-semibold mb-1">Síntesis del Día</h4>
            <p className="text-gray-300 leading-relaxed">
              El par <span className="text-green-400 underline">{displayData.symbol}</span> muestra una{' '}
              <span className={trendColor}>{trendText}</span> el {dateStr}. {displayData.summary}
            </p>
          </div>

          <div className="flex items-center gap-2 text-xs text-gray-400">
            <span>Timeframe: {displayData.timeframe}</span>
            <span>•</span>
            <span>Última actualización: {format(new Date(), 'HH:mm')}</span>
          </div>
        </div>
      </div>
    </AIRefreshOverlay>
  );
}
