import { useState, useEffect, useRef } from 'react';
import { Loader2 } from 'lucide-react';
import { useTechnicalLevels } from '@/hooks/useAnalysisData';
import { useAIAnalysis } from '@/hooks/useAIAnalysis';
import { AnalysisError } from './AnalysisError';
import { AIRegenerateButton } from './AIRegenerateButton';
import { AIRefreshOverlay } from './AIRefreshOverlay';

interface TechnicalLevelsProps {
  symbol: string;
  currentPrice: number;
  realtimePrice?: number;
  isRealtimeConnected?: boolean;
}

export function TechnicalLevels({ symbol, currentPrice, realtimePrice, isRealtimeConnected }: TechnicalLevelsProps) {
  const effectivePrice = realtimePrice || currentPrice;
  const { data, isLoading, error } = useTechnicalLevels(symbol, effectivePrice);
  const { generateAnalysis, isLoading: isAILoading } = useAIAnalysis();
  const [aiLevels, setAILevels] = useState<Record<string, unknown> | null>(null);
  const prevSymbolRef = useRef<string | null>(null);
  const hasAutoGenerated = useRef(false);

  // Reset AI data when symbol changes
  useEffect(() => {
    if (symbol && symbol !== prevSymbolRef.current) {
      prevSymbolRef.current = symbol;
      hasAutoGenerated.current = false;
      setAILevels(null);
    }
  }, [symbol]);

  // Auto-generate AI analysis when we have price data
  useEffect(() => {
    if (symbol && effectivePrice > 0 && !hasAutoGenerated.current && !isAILoading) {
      hasAutoGenerated.current = true;
      
      generateAnalysis('technical_levels', symbol, {
        currentPrice: effectivePrice,
        previousClose: effectivePrice * 0.998,
        high: effectivePrice * 1.01,
        low: effectivePrice * 0.99
      }).then(result => {
        if (result?.analysis) {
          setAILevels(result.analysis);
        }
      });
    }
  }, [symbol, effectivePrice, generateAnalysis, isAILoading]);

  const handleRegenerateWithAI = async () => {
    const result = await generateAnalysis('technical_levels', symbol, {
      currentPrice: effectivePrice,
      previousClose: effectivePrice * 0.998,
      high: effectivePrice * 1.01,
      low: effectivePrice * 0.99
    }, undefined, undefined, true); // forceRefresh = true
    if (result?.analysis) {
      setAILevels(result.analysis);
    }
  };

  if (isLoading) {
    return (
      <div className="bg-[#0a1a0a] border border-green-900/50 rounded-lg p-4">
        <div className="flex items-center justify-center py-8">
          <Loader2 className="w-6 h-6 text-green-400 animate-spin" />
          <span className="ml-2 text-gray-400">Cargando niveles técnicos...</span>
        </div>
      </div>
    );
  }

  if (error || !data) {
    return (
      <AnalysisError 
        title="Niveles Técnicos"
        error={error as Error}
        compact
      />
    );
  }

  // Merge AI levels with base data if available
  const displayData = aiLevels ? {
    ...data,
    pivot: (aiLevels.pivot as number) || data.pivot,
    resistances: (aiLevels.resistances as typeof data.resistances) || data.resistances,
    supports: (aiLevels.supports as typeof data.supports) || data.supports,
    fibonacci: (aiLevels.fibonacci as typeof data.fibonacci) || data.fibonacci,
  } : data;

  const getStrengthBadge = (strength: 'strong' | 'moderate' | 'weak') => {
    switch (strength) {
      case 'strong': return 'bg-green-500/20 text-green-400 border-green-500/30';
      case 'moderate': return 'bg-yellow-500/20 text-yellow-400 border-yellow-500/30';
      case 'weak': return 'bg-gray-500/20 text-gray-400 border-gray-500/30';
    }
  };

  const getStrengthLabel = (strength: 'strong' | 'moderate' | 'weak') => {
    switch (strength) {
      case 'strong': return 'Fuerte';
      case 'moderate': return 'Moderado';
      case 'weak': return 'Débil';
    }
  };

  return (
    <AIRefreshOverlay isRefreshing={isAILoading}>
      <div className="bg-[#0a1a0a] border border-green-900/50 rounded-lg p-4">
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-white font-semibold flex items-center gap-2">
            Niveles Técnicos - Soportes y Resistencias
            {aiLevels && (
              <span className="text-xs text-purple-400 bg-purple-500/20 px-2 py-0.5 rounded">IA</span>
            )}
          </h3>
          <AIRegenerateButton 
            onClick={handleRegenerateWithAI} 
            isLoading={isAILoading}
            showLabel={false}
            size="icon"
            className="h-7 w-7"
          />
        </div>
        
        <div className="space-y-4 text-sm">
          {/* Pivot Point */}
          <div className="flex items-center justify-between p-3 bg-[#0d1f0d] rounded-lg">
            <span className="text-gray-400">Punto Pivote</span>
            <span className="text-white font-mono font-bold">{displayData.pivot.toFixed(4)}</span>
          </div>

          {/* Resistances */}
          <div>
            <h4 className="text-gray-400 mb-2">Resistencias Clave:</h4>
            <div className="space-y-2">
              {displayData.resistances.map((level, index) => (
                <div key={index} className="flex items-start gap-2 p-2 bg-[#0d1f0d] rounded">
                  <span className="text-red-400 font-mono font-bold shrink-0">{level.level.toFixed(4)}</span>
                  <span className={`px-2 py-0.5 text-xs rounded border ${getStrengthBadge(level.strength)}`}>
                    {getStrengthLabel(level.strength)}
                  </span>
                  {level.description && (
                    <span className="text-gray-400 text-xs">{level.description}</span>
                  )}
                </div>
              ))}
            </div>
          </div>

          {/* Supports */}
          <div>
            <h4 className="text-gray-400 mb-2">Soportes Clave:</h4>
            <div className="space-y-2">
              {displayData.supports.map((level, index) => (
                <div key={index} className="flex items-start gap-2 p-2 bg-[#0d1f0d] rounded">
                  <span className="text-green-400 font-mono font-bold shrink-0">{level.level.toFixed(4)}</span>
                  <span className={`px-2 py-0.5 text-xs rounded border ${getStrengthBadge(level.strength)}`}>
                    {getStrengthLabel(level.strength)}
                  </span>
                  {level.description && (
                    <span className="text-gray-400 text-xs">{level.description}</span>
                  )}
                </div>
              ))}
            </div>
          </div>

          {/* Fibonacci Levels */}
          {displayData.fibonacci && displayData.fibonacci.length > 0 && (
            <div>
              <h4 className="text-gray-400 mb-2">Niveles Fibonacci:</h4>
              <div className="grid grid-cols-3 gap-2">
                {displayData.fibonacci.map((fib, index) => (
                  <div key={index} className="text-center p-2 bg-[#0d1f0d] rounded">
                    <p className="text-blue-400 text-xs">{fib.level}</p>
                    <p className="text-white font-mono text-xs">{fib.price.toFixed(4)}</p>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </AIRefreshOverlay>
  );
}
